### ISSUE TITLE
Unable to run Jekyll serve 

### ISSUE THREAD

**Issue by deepakmani** [mpalmer/jekyll-static-comments#17]
Hi Matt,
Thanks for your script.

I'm just using the plugin on Jekyll 1.4.3 to generate comments and completed the following steps
1. Created a comment in the comments folder
2. Populated posts 
and ran jekyll serve
I get the following message after all the posts have been parsed.

 Invalid Date: '' is not a valid datetime.
  Liquid Exception: exit in feed.xml

For each post it appears to be running the script twice also...

Thanks,
Deepak

**Comment by IQAndreas** [comment]
Post one of your sample comments; this is just a guess, but it seems like the `Date` field either doesn't exist on, or is empty in one or more of the comments.

**Comment by deepakmani** [comment]
Thanks for the reply.
I read your post: https://github.com/IQAndreas/jekyll-static-comments/commit/ce7808d9ef7a127bac52de470e6d83cbfaf78457  and it helped fix the error as I use jekyll 1.4.3. 
I think this needs to be mentioned somewhere in the main page. recursion was making things tricky to debug.
Do you need to use post.comments to access the liquid hash, instead of page.comments as mentioned in the Readme.
