### ISSUE TITLE
`{% if c.link %}` working incorrectly

### ISSUE THREAD

**Issue by IQAndreas** [mpalmer/jekyll-static-comments#2]
See the following line:
https://github.com/mpalmer/jekyll-static-comments/blob/master/comment_template.html#L12

If the "link" property exists on a comment, but is empty (ie `link: ''`. This happens when no link was filled into the box when they submitted the comment) the `{% if c.link %}` will execute the `true` block of code, when it should be executing the `false` one. 

It should be a really quick fix, I'm just not sure how to check if a string is empty in the template's language. (What is the language name by the way? It's difficult to Google for help without knowing it)

**Comment by mpalmer** [comment]
The template language that Jekyll uses is Liquid.  Doesn't make it all that much easier to google.  There are links to tutorials and information about it from the main [Jekyll wiki](https://github.com/mojombo/jekyll/wiki/Liquid-Extensions).

Enhancements to the default example template appreciated.
